name: ci

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features std"
          - "--features nightly"
          - "--features nightly,std"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --no-default-features ${{ matrix.args }}
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features std"
          - "--features nightly"
          - "--features nightly,std"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo clippy --no-default-features ${{ matrix.args }} -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo rustdoc --all-features
